### ISSUE TITLE
[QUESTION] Quad other side is black

### ISSUE THREAD

**Issue by vamidi** [kosua20/Rendu#4]
Hi, amazing opengl renderer and other tools you created! I was trying to use your renderer as a reference, but I got an issue with a quad that I try to render. Do you might know why this is happening?

https://gyazo.com/5b98f6da8648f59269c80cc7751b4ece

**Comment by kosua20** [comment]
Hi, thank you!
This is caused by the Screen Space Ambient Occlusion approach I'm using right now, I need to investigate this artefact in details. Either I have a bug in my current SSAO implementation, or I should move to a more advanced technique (Horizon-Based Ambient Occlusion for instance).

**Comment by vamidi** [comment]
Ahhh right, but I think I overlooked something. I will try and comment out the SSAO out and see if that was the case.

**Comment by vamidi** [comment]
I tested it out really quick and it worked! so it has to do with SSAO. I will check the learnopengl website to learn more about it. Do you have any pointers to keep in mind?

**Comment by vamidi** [comment]
@kosua20 also if I can squeeze one more question here. how come that my quads and everything is shiny in comparison to yours? I have the same values. also on the inside they are reflecting the world, but in your scene they don't

**Comment by kosua20** [comment]
So thinking about it a bit more, the explanation is that I'm rendering the sides of the box with bakface culling disabled. But the geometry normals are still pointing towards the inside of the box, so when computing SSAO on the outside, it gets maximally occluded.
If you want some intro resources about SSAO: https://learnopengl.com/Advanced-Lighting/SSAO, http://john-chapman-graphics.blogspot.com/2013/01/ssao-tutorial.html

For the shininess, I'm not sure. What value are you using in the roughness and metalness map ?

**Comment by vamidi** [comment]
The shiny values are the same. I am using the same textures to see if everything matches. Is it because i dont have shadows? Also saw the commit it makes sense :O! Awesome update

**Comment by kosua20** [comment]
If it still looks like the screenshot you posted above, it is weird. It seems that everything is treated as extremely specular. Could you share you scene file, just to check that I have the same issue on my machine? (my email adress is on my profile). Thanks!
